# Building an LLM from Scratch

### Uncomment line below if torch is not already installed in your environment

In [1]:
#%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu128

In [ ]:
import torch

### I want to test how a basic Neural Network functions, so I'm creating a basic Neural Network with only a few layers to experiment with

In [ ]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()

        self.layers = torch.nn.Sequential(

            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30), # Linear layer takes the number of input and output nodes as arguments
            torch.nn.ReLU(),                 # Nonlinear activation functions are placed between the hidden layers
    
            # 2nd hidden layer
            torch.nn.Linear(30, 20),         # The number of output nodes of one hidden layer had to match the number of input nodes of the next layer
            torch.nn.ReLU(),
    
            # Output layer
            torch.nn.Linear(20, num_outputs)
        )
        
    def forward(self, x):
        logits = self.layers(x)
        return logits                        # The outputs of the last layer are called logits

In [ ]:
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


### As a core part of training AI models is gradient descent through  I want to analyze the structure of the parameters that will be adjusted

In [ ]:
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print("Total number of trainable model parameters:", num_params)

Total number of trainable model parameters: 2213


In [ ]:
print(model.layers[0].weight)
print(model.layers[0].weight.shape)

Parameter containing:
tensor([[ 0.0912, -0.0079,  0.0986,  ...,  0.1380,  0.1168, -0.0422],
        [ 0.1122, -0.1248, -0.0221,  ..., -0.0280, -0.0832, -0.0772],
        [-0.0183, -0.1042, -0.0098,  ..., -0.0876,  0.0159, -0.0177],
        ...,
        [-0.0765,  0.1294,  0.1259,  ...,  0.0808, -0.0528,  0.0588],
        [ 0.0305, -0.0990,  0.0379,  ...,  0.0017,  0.0710,  0.0030],
        [ 0.0532, -0.0369,  0.0347,  ..., -0.0615,  0.1393,  0.1010]],
       requires_grad=True)
torch.Size([30, 50])


In [ ]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


### When a gradient is computed within the model it keeps track of each operation for the calculation of the parameters partial derivatives

In [ ]:
torch.manual_seed(123)
X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


In [ ]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


### Initializing testing data to experiment with

In [ ]:
X_train = torch.tensor([
    [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])
y_train = torch.tensor([0, 0, 0, 1, 1])

X_test = torch.tensor([
    [-0.8, 2.8],
    [2.6, -1.6],
])
y_test = torch.tensor([0, 1])

In [ ]:
from torch.utils.data import Dataset

class ToyDataset(Dataset):
    def __init__(self, X, y):
        self.features = X
        self.labels = y

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y

    def __len__(self):
        return self.labels.shape[0]

In [ ]:
train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

In [ ]:
print(len(train_ds))

5


### In order to make the process of training more streamlined im creating a simple DataLoader which will handle the batching among other data preprocessing when used while training

In [ ]:
from torch.utils.data import DataLoader

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0        # The number of subprocesses used to batch the dataset: useful for large datasets and allows GPU to batch while CPU prepares
)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

In [ ]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


In [ ]:
# Having a substantially smaller batch as the last batch in a training epoch can disturb the convergence during training.
# To prevent this we will set drop_last=True.
train_loader = DataLoader(
    dataset=train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)

In [ ]:
for idx, (x, y) in enumerate(train_loader):
    print(f"Batch {idx+1}:", x, y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


### Creating the training loop and examining the process and loss outputs

In [ ]:
import torch.nn.functional as F

torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2) # The toy dataset has 2 features and 2 classes
optimizer = torch.optim.SGD(
    model.parameters(), lr=0.5                     # The optimizer needs to know which parameters to optimize
)

num_epochs = 3
for epoch in range(num_epochs):
    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        logits = model(features)

        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()                     # Sets the gradients from the previous round to 0 to prevent unintended gradient accumulation
        loss.backward()                           # Computes the gradients of the loss given the model parameters
        optimizer.step()                          # The optimizer used the gradients to update the model parameters

        ## LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx+1:03d}/{len(train_loader):03d}"
              f" | Train Loss: {loss:.2f}")

    model.eval()
    # Insert optional model evaluation code

Epoch: 001/003 | Batch 001/002 | Train Loss: 0.75
Epoch: 001/003 | Batch 002/002 | Train Loss: 0.65
Epoch: 002/003 | Batch 001/002 | Train Loss: 0.44
Epoch: 002/003 | Batch 002/002 | Train Loss: 0.13
Epoch: 003/003 | Batch 001/002 | Train Loss: 0.03
Epoch: 003/003 | Batch 002/002 | Train Loss: 0.00


### Now that the model is trained I'm going to make some predictions with it and look at how it represents the data

In [ ]:
model.eval()
with torch.no_grad():
    outputs = model(X_train)
print(outputs)

tensor([[ 2.8569, -4.1618],
        [ 2.5382, -3.7548],
        [ 2.0944, -3.1820],
        [-1.4814,  1.4816],
        [-1.7176,  1.7342]])


In [ ]:
torch.set_printoptions(sci_mode=False)  # Make outputs more legible
probas = torch.softmax(outputs, dim=1)
print(probas)

tensor([[0.9991, 0.0009],
        [0.9982, 0.0018],
        [0.9949, 0.0051],
        [0.0491, 0.9509],
        [0.0307, 0.9693]])


In [ ]:
predictions = torch.argmax(probas, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [ ]:
# We can apply the argmax function to the logits (outputs) directly
predictions = torch.argmax(outputs, dim=1)
print(predictions)

tensor([0, 0, 0, 1, 1])


In [ ]:
predictions == y_train

tensor([True, True, True, True, True])

In [ ]:
torch.sum(predictions == y_train)

tensor(5)

### Creating a function to generalize the concept of model accuracy and account for arbitrarily large datasets by computing correctness in batches

In [ ]:
def compute_accuracy(model, dataloader):
    
    model = model.eval()
    correct = 0.0
    total_examples = 0

    for idx, (features, labels) in enumerate(dataloader):

        with torch.no_grad():
            logits = model(features)

        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions      # Returns a tensor of True/False values depending on whether the labels match
        correct += torch.sum(compare)        # Count the number of True values (Since compare is a Tensor correct's type is promoted to a Tensor following the calculation to preserve Tensor properties)
        total_examples += len(compare)

    return (correct / total_examples).item() # The fraction of correct prediction, a value between 0 and 1. .item() returns the value of the tensor as a Python float

In [ ]:
print(compute_accuracy(model, train_loader))

1.0


In [ ]:
print(compute_accuracy(model, test_loader))

1.0


### Seeing how to save a model's parameters to the disk and load a saved models parameters into a starting model instance

In [ ]:
torch.save(model.state_dict(), "model.pth") # "model.pth" can be any arbitrary name and file ending, however, .pth and .pt are convention

In [ ]:
model = NeuralNetwork(2, 2)
model.load_state_dict(torch.load("model.pth")) # An instance of the model in memory is required to apply the saved parameters

<All keys matched successfully>

### Exploring how to optimize performance with GPUs

In [ ]:
# Check if the version of PyTorch has GPU compatability
print(torch.cuda.is_available())

True


In [ ]:
tensor_1 = torch.tensor([1., 2., 3.])
tensor_2 = torch.tensor([4., 5., 6.])
print(tensor_1 + tensor_2)

tensor([5., 7., 9.])


In [ ]:
tensor_1 = tensor_1.to("cuda")  # Changing datatype of tensor_1; can specify which GPU to locate tensor on through .to("cuda:0") or .to("cuda:1")
tensor_2 = tensor_2.to("cuda")
print(tensor_1 + tensor_2)

tensor([5., 7., 9.], device='cuda:0')


In [ ]:
# NOTE: This cell is intended to return an error to see what happens when tensors are on different devices
tensor_1 = tensor_1.to("cpu")   # All tensors used in a computation must be on the same device or they will fail
print(tensor_1 + tensor_2)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Since what I'm using to test my Neural Network is a small dataset we won't notice an increase in performance because of the transfer cost from CPU to GPU. 
### However, this will be usefull when training deep neural networks, especially LLMs.

In [ ]:
device = torch.device("cuda") # Defines a device variable that defaults to a GPU

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # Make the device able to run on CPU if GPU not available

In [ ]:
# The following code is for Mac's which an Apple Silicon chip (like the M1, M2, M3, and newer models)
"""
device = torch.device(
    "mps" if torch.backends.mps.is_available() else "cpu"
)
"""

'\ndevice = torch.device(\n    "mps" if torch.backends.mps.is_available() else "cpu"\n)\n'

In [ ]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2) # The toy dataset has 2 features and 2 classes

model = model.to(device)                           # Transfers the model onto the GPU

optimizer = torch.optim.SGD(
    model.parameters(), lr=0.5                     # The optimizer needs to know which parameters to optimize
)

num_epochs = 3

for epoch in range(num_epochs):
    model.train()

    for batch_idx, (features, labels) in enumerate(train_loader):
        features, labels = features.to(device), labels.to(device) # Transfers the data onto the GPU
        logits = model(features)

        loss = F.cross_entropy(logits, labels)

        optimizer.zero_grad()                     # Sets the gradients from the previous round to 0 to prevent unintended gradient accumulation
        loss.backward()                           # Computes the gradients of the loss given the model parameters
        optimizer.step()                          # The optimizer used the gradients to update the model parameters

        ## LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx+1:03d}/{len(train_loader):03d}"
              f" | Train Loss: {loss:.2f}")

    model.eval()
    # Insert optional model evaluation code

Epoch: 001/003 | Batch 001/002 | Train Loss: 0.75
Epoch: 001/003 | Batch 002/002 | Train Loss: 0.65
Epoch: 002/003 | Batch 001/002 | Train Loss: 0.44
Epoch: 002/003 | Batch 002/002 | Train Loss: 0.13
Epoch: 003/003 | Batch 001/002 | Train Loss: 0.03
Epoch: 003/003 | Batch 002/002 | Train Loss: 0.00


### Training with multiple GPUs

I will be experimenting with a Distributed Data Parallel (DDP) strategy for utilizing multiple GPUs. However, DDP does not function properly within interactivePython environments like Jupyter notebooks, as they dont handle multiprocessing in the same way that a standalone Python script does. 

Therefore, the following code of my experimentation will be executed as a script as DDP needs to spawn multiple processes, and each process should have its own Python interpreter instance.

The code will be located at the following link in my GitHub repo for this project: https://github.com/Plehndm/LLM_From_Scratch/blob/main/DDP_Multiprocessing_Test.py

As I am doing this on a Windows laptop I had to install WSL2 to run Ubuntu (any linux distro should work) and reinstall torch inside a python virtual environment, running the script within it.

### Tokenizing Text

I will now experiment with tokenizing text for preprocessing data before LLM training.

In [ ]:
with open('the-verdict.txt', 'r') as f:
    raw_text = f.read()
print("Total number of characters:", len(raw_text))
print(raw_text[:99])

Total number of characters: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [ ]:
import re
text = "Hello, world. This, is a test."
result = re.split(r'(\s)', text)          # This will split the following text on whitespaces but keeps them in the result
print(result)

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']


In [ ]:
result = re.split(r'([.,]|\s)', text)     # This will split the following text additionally on commas and periods but still keeps whitespases in the result
print(result)

['Hello', ',', '', ' ', 'world', '.', '', ' ', 'This', ',', '', ' ', 'is', ' ', 'a', ' ', 'test', '.', '']


In [ ]:
# However, we don't want these redundant whitespace characters for simplicity and berevity of the tokenized outputs
# But, whitespaces can be helpful in datasets in applications where the exact structure of the sentence is needed such as python code
result = [item for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'This', ',', 'is', 'a', 'test', '.']


In [ ]:
# Now lets add more different punctuations that we can tokenize
text = "Hello, world. Is this-- a test? Tests are good; Only for: worlds, code, and more"
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?', 'Tests', 'are', 'good', ';', 'Only', 'for', ':', 'worlds', ',', 'code', ',', 'and', 'more']


In [ ]:
preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
print(len(preprocessed))
print(preprocessed[:30])

4690
['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in']


In [ ]:
# We will see how many unique tokens there are 
all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
print(vocab_size)

1130


In [ ]:
# Creating the vocabulary to be used for token ID conversion
vocab = {token:integer for integer,token in enumerate(all_words)}
for i, item in enumerate(vocab.items()):
    print(item)
    if i >= 50:
        break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


In [ ]:
class SimpleTokenizerV1:
    def __init__(self, vocab):
        self.str_to_int = vocab                          # Stores the vocabulary as a class attribute for access in the encode and decode methods
        self.int_to_str = {id:token for token,id in vocab.items()} # Creates an inverse vocabulary that maps token IDs back to the original text tokens

    def encode(self, text):                              # Processes input text into token IDs
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]
        ids = [self.str_to_int[token] for token in preprocessed]
        return ids
    
    def decode(self, ids):                               # Converts IDs back into text
        text = " ".join([self.int_to_str[id] for id in ids])
        text = re.sub(r'\s+([,.:;?_!"()\']|--)', r'\1', text) # Removes spaces before the specified punctuation
        return text

In [ ]:
tokenizer = SimpleTokenizerV1(vocab)
text = """"It's the last he painted, you know," Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)
print(tokenizer.decode(ids))

[1, 56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]
" It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


In [ ]:
# NOTE: This is supposed to error
# This showcases what happens when our vocabulary doesn't have an extensive enough list
text = "Hello, do you like tea?"
print(tokenizer.encode(text))

KeyError: 'Hello'

### Special Tokens

Now we will see how adding additinal special tokens can be used to provide further context for an LLM during training.

In [ ]:
all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"]) 
# <|endoftext|> symbolizes the end of independent texts and <|unk|> symbolozes an unknown word not in our training set
vocab = {token:integer for integer,token in enumerate(all_tokens)} 
print(len(vocab.items()))

1132


In [ ]:
for item in list(vocab.items())[-5:]:
    print(item)

('younger', 1127)
('your', 1128)
('yourself', 1129)
('<|endoftext|>', 1130)
('<|unk|>', 1131)


In [ ]:
class SimpleTokenizerV2:
    def __init__(self, vocab):
        self.str_to_int = vocab                          # Stores the vocabulary as a class attribute for access in the encode and decode methods
        self.int_to_str = {id:token for token,id in vocab.items()} # Creates an inverse vocabulary that maps token IDs back to the original text tokens

    def encode(self, text):                              # Processes input text into token IDs
        preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
        preprocessed = [item.strip() for item in preprocessed if item.strip()]

        preprocessed = [item if item in self.str_to_int else "<|unk|>" for item in preprocessed] # Replaces unknown words with <|unk|> token
        ids = [self.str_to_int[token] for token in preprocessed]

        return ids
    
    def decode(self, ids):                               # Converts IDs back into text
        text = " ".join([self.int_to_str[id] for id in ids])
        text = re.sub(r'\s+([,.:;?_!"()\']|--)', r'\1', text) # Removes spaces before the specified punctuation
        return text

In [ ]:
text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = " <|endoftext|> ".join((text1, text2))
print(text)

Hello, do you like tea? <|endoftext|> In the sunlit terraces of the palace.


In [ ]:
# Now lets test if our new tokenizer works as expected
tokenizer = SimpleTokenizerV2(vocab)
print(tokenizer.encode(text))
print(tokenizer.decode(tokenizer.encode(text)))

[1131, 5, 355, 1126, 628, 975, 10, 1130, 55, 988, 956, 984, 722, 988, 1131, 7]
<|unk|>, do you like tea? <|endoftext|> In the sunlit terraces of the <|unk|>.


### Byte Pair Encoding

More sophisticated tokenization scheme based on breaking down words into subwords by grouping together commonly occuring characters into a new token. This also solves the Out of Vocabulary (OOV) problem we just faced because if an LL encounters a word it doen't understand it can break it down into subwords that it does, instead of being stuck or left woth an <|unk|> token it can't do anything with.

In [ ]:
# Python library to make byte pair encoding easy to implement uncomment if not already installed
#%pip install tiktoken

   ---------------------------------------- 0.0/874.8 kB ? eta -:--:--
   ---------------------------------------- 874.8/874.8 kB 7.3 MB/s  0:00:00

   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ----- ---------------------------------- 1/7 [regex]
   ----- ---------------------------------- 1/7 [regex]
   ----------- ---------------------------- 2/7 [idna]
   ----------- ---------------------------- 2/7 [idna]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ---------------------- ----------------- 4/7 [certifi]
   ---------------------------- ----------- 5/7 [requests]
   ------------

In [ ]:
from importlib.metadata import version
import tiktoken
print("tiktoken version:", version("tiktoken"))

tiktoken version: 0.13.0


In [ ]:
tokenizer = tiktoken.get_encoding("gpt2")

In [ ]:
text = (
    "Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace."
)
integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

strings = tokenizer.decode(integers)
print(strings)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 554, 262, 4252, 18250, 8812, 2114, 286, 617, 34680, 27271, 13]
Hello, do you like tea? <|endoftext|> In the sunlit terraces of someunknownPlace.


In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [ ]:
enc_sample = enc_text[50:]

In [ ]:
context_size = 4                 # The context size determines how many tokens are included in the input
x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]
print(f"x:  {x}")
print(f"y:       {y}")

x:  [290, 4920, 2241, 287]
y:       [4920, 2241, 287, 257]


In [ ]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [ ]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a


In [ ]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        token_ids = tokenizer.encode(txt)                        # Tokenizes the entire text

        for i in range(0, len(token_ids) - max_length, stride):  # Uses a sliding window to chunk the book into overlapping sequences of max_length
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):                                           # Returns the total number of rows in the dataset
        return len(self.input_ids)
    
    def __getitem__(self, idx):                                  # Returns a single row from the dataset
        return self.input_ids[idx], self.target_ids[idx]

In [ ]:
def create_dataloader_v1(txt, batch_size=4, max_length=256, stride=128, 
                         shuffle=True, drop_last=True, num_workers=0):
    tokenizer = tiktoken.get_encoding("gpt2")                    # Initialize tokenizer
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)   # Create dataset
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,                                     # drop_last = True drops the last batch if it is shorter than the specified batch_size to prevent loss spikes during training
        num_workers=num_workers                                  # The number of CPU processes to use for preprocessing
    )

    return dataloader

In [ ]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

dataloader = create_dataloader_v1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)
data_iter = iter(dataloader)                  # Converts dataloader into a Python iterator to fetch the next entry via Python's built in next() function
first_batch = next(data_iter)
print(first_batch)